name: Running Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-go@v4
      with:
        go-version: "1.17"
    - run: |
        go test -v ./...
